### ISSUE TITLE
Pandoc

### ISSUE THREAD

**Issue by vwbusguy** [edunham/resume#1]
Not really an issue - more of a feature request.  First, thanks for this!  I might fork it as an academic CV builder as I've outgrown LibreOffice for my CV.  

I noticed you host your resume on your site.  Have you considered using Pandoc (http://pandoc.org/) to generate it as HTML as well as pdf?  You could also add another level of abstraction to putting your data in Markdown and have Pandoc parse it into LaTeX from md.  If you'd like I could put together a pull request to demonstrate it from md.

**Comment by edunham** [comment]
Thanks for the feedback! 

In my own case, I'm pretty vain about having my resume display just right (avoiding awkward line breaks, broken fonts, etc.), so putting a pdf online has made more sense than generating HTML. I have a feeling that if I try to build a system which can emit both pretty HTML and pretty LaTeX PDFs, it'll sprawl out to involve at least a templating engine and possibly a database, and then I'll realize that I'm making something I never set out to build and be sad. I've [dug around in Pandoc a bit](http://edunham.net/2015/03/05/hieroglyph2beamer_with_pandoc.html) for other projects.

If you'd like to build a thing that makes pretty LaTeX and HTML resumes from markdown, it'd probably be more appropriate to keep it in a repo you own and maintain, but I'd be happy to link it from my README for people who're seeking those features!

**Comment by vwbusguy** [comment]
I totally understand - that's why I've shyed away from publican for some
recent doc projects. Thanks again for sharing your work on this!

Scott

**Comment by edunham** [comment]
Relatedly (because it's a cool link and if I put it here I'll remember it), https://github.com/davidmerfield/typeset might be of assistance in a project that tries to make an HTML page render comparably to LaTeX.

**Comment by edunham** [comment]
Closing for now, but do let me know (issues, email, PR, whatever) if you build a thing that I should be linking from the README!
